<script>
    let y ;
    import { fly } from "svelte/transition"
    import { quintInOut} from "svelte/easing"
    export let heading
</script>

<svelte:window bind:scrollY={y}/>

{#if y >= -100}
<div class="sm:flex sm:visible hidden font-firasans pl-3 " in:fly={{x:-100, easing:quintInOut,delay:300}}>
    <div>
        <h2 class="text-xl font-semibold mt-3">
            {heading}
        </h2>
        <p class="text-[#9A9A9A] text-sm">Art work generated by public</p>
    </div>
</div>
{/if}